os:
  - osx

language: node_js
node_js: stable

script:
  - hexo clean
  - hexo g
  # - hexo algolia
after_script:
  - cd public
  - git init
  - git config user.name "0GGmr0"
  - git config user.email "18817619557@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push -f "https://${GH_TOKEN}@${GH_REF}" master:master
branches:
  only:
    - source-code
env:
 global:
   - GH_REF: github.com/0GGmr0/0GGmr0.github.io
